# Generated by Django 4.2.21 on 2025-05-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inn", models.CharField(max_length=12, unique=True)),
                ("balance", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="BalanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_id", models.UUIDField(unique=True)),
                ("delta", models.BigIntegerField()),
                ("document_number", models.CharField(max_length=64)),
                ("document_date", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_logs",
                        to="api.organization",
                    ),
                ),
            ],
        ),
    ]
